#docker-compose up -d
#docker-compose -f "docker-compose.yml" up -d --build web
version: "3.8"
services:
  backend:
    hostname: backend
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
    - DB_PASSWORD=postgres
    - DB_USER=postgres
    - DB_NAME=postgres
    - DB_HOST=db
    - DB_DRIVER=pgsql
    ports:
    - "80:80"
    volumes:
    - ./:/host_machine/:rw
    - source_code:/root/source_code:rw
    depends_on:
    - db

  frontend:
    hostname: frontend
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./:/host_machine/:rw
    - source_code:/root/source_code:rw

  db:
    image: postgres:13
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=practice_db_1
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
    - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  source_code:
#volumes:
#  mysql_data: { driver: local }