#docker-compose up -d
#docker-compose -f "docker-compose.yml" up -d --build web
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
    - DB_PASSWORD=postgres
    - DB_USER=postgres
    - DB_NAME=postgres
    - DB_HOST=db
    - DB_DRIVER=pgsql
    ports:
    - "80:80"
    - "3000:3000"
    volumes:
    - ./:/host_machine/:rw
#    hostname: "mycontainer"
    depends_on:
    - db

  db:
    image: postgres:13
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=practice_db_1
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
#    - "mysql_data:/var/lib/mysql"
    - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

#volumes:
#  mysql_data: { driver: local }