<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Drug;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Drug>
 */
class DrugFactory extends Factory
{
    protected $model = Drug::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $din = '000'.$this->faker->randomNumber(5, true);

        return [
            'din' => $din,
            'din_pin' => $din,
            'drug_or_product_name' => $this->faker->words(2, true),
            'drug_or_product_name',
            'din_duplicate' => '',
            'health_canada_drug_name' => $this->faker->words(3, true),
            'reformulary' => '1',
            'rg_tier' => $this->faker->randomElement(['1', '2', '3', 'Exclude', 'Restricted', 'SA']),
            'conditions' => '',
            'drug_product_type' => $this->faker->randomElement(['Biosimilar', 'Generic', 'Brand', '']),
            'medical_condition' => '',
            'sub_medical_condition' => '',
            'drug_class' => $this->faker->randomElement(['Urinary Analgesics', 'Anticholinergic Agents Combination', 'Potassium Binders', 'Vitamins/Minerals', 'Antivirals + Corticosteroids Combination']),
            'active_ingredient' => $this->faker->randomElement(['haemophilus influenzae type b-prp and tetanus toxoid conjugate (prp-t)', 'fluticasone propionate', 'imiglucerase', 'carglumic acid', 'pyridostigmine bromide']),
            'gf_period_code' => '',
            'gf_period' => '',
            'step_therapy' => '',
            'quantity_limits' => '',
            'action' => '',
            'explanation' => '',
            'slf' => '1',
            'slf_tier' => $this->faker->randomElement(['1', '2', '3']),
            'slf_action' => '',
            'slf_external_notes' => '',
            'slf_gf_period' => '',
            'slf_ql' => '',
            'slf_gf_period_code' => '',
            'slf_screencode' => '',
            'slf_visible_on_website' => '1',
            'slf_rationale_code' => '',
            'clic' => '1',
            'clic_tier' => $this->faker->randomElement(['1', '2', '3']),
            'clic_action' => '',
            'clic_external_notes' => '',
            'clic_gf_period' => '',
            'clic_targetted_letter' => '',
            'clic_ql' => '',
            'sa' => '',
            'clic_gf_period_code' => '',
            'clic_screencode' => '',
            'clic_visible_on_website' => '',
            'clic_rationale_code' => '',
            'gwl' => '1',
            'gwl_tier' => $this->faker->randomElement(['1', '2', '3']),
            'gwl_action' => '',
            'gwl_gf_period_code' => '',
            'gwl_screencode' => '',
            'gwl_visible_on_website' => '',
            'gwl_rationale_code' => '',
            'gwl_cada' => '1',
            'gwl_cada_tier' => $this->faker->randomElement(['1', '2', '3']),
            'gwl_cada_action' => '',
            'gwl_cada_screencode' => '',
            'gwl_cada_visible_on_website' => '',
            'gwl_cada_rationale_code' => '',
            'cs' => '1',
            'cs_tier' => $this->faker->randomElement(['1', '2', '3']),
            'cs_action' => '',
            'cs_external_notes' => '',
            'cs_gf_period' => '',
            'cs_gf_period_code' => '',
            'cs_screencode' => '',
            'cs_visible_on_website' => '',
            'cs_rationale_code' => '',
            'cs_notes' => '',
            'cs_iw' => '1',
            'cs_iw_tier' => $this->faker->randomElement(['1', '2', '3']),
            'cs_iw_action' => '',
            'cs_iw_gf_period' => '',
            'cs_iw_gf_period_code' => '',
            'cs_iw_screencode' => '',
            'cs_iw_visible_on_website' => '',
            'cs_iw_rationale_code' => '',
            'jg' => '1',
            'jg_tier' => $this->faker->randomElement(['1', '2', '3']),
            'jg_sa' => '',
            'jg_notes' => '',
            'jg_action' => '',
            'jg_explanation' => '',
            'jg_gf_period' => '',
            'jg_ql' => '',
            'jg_gf_period_code' => '',
            'jg_screencode' => '',
            'jg_visible_on_website' => '',
            'jg_rationale_code' => '',
            'generic_name' => '',
            'generic_version_of' => '',
            'screen_code' => '',
            'newscreencode_1' => '',
            'visible_on_website' => '1',
            'blue_box' => '',
            'alternative_dins' => '',
            'alternative_dins_non_prescribed' => '',
            'strength' => '',
            'form' => $this->faker->randomElement(['OIL', 'KIT+LOTION+CREAM', 'POWDER FOR SUSPENSION', 'TABLET', 'LIQUID, POWDER FOR SOLUTION']),
            'route_of_administration' => '',
            'drug_sub_type' => $this->faker->randomElement(['Biosimilar', 'SS Brand', 'Generic', 'MS Brand']),
            'manufacturer' => $this->faker->randomElement(['INNO-VITE INCORPORATED', 'WILC HEALTHCARE INC', 'NOVO NORDISK CANADA INC', 'BENTEC PHARMA INC']),
            'discontinued_date' => '',
            'notes' => '',
            'schedule' => '',
            'drug_or_product_name_french' => '',
            'medical_condition_french' => '',
            'sub_medical_condition' => '',
            'drug_class_french' => '',
            'active_ingredient_french' => '',
            'generic_name_french' => '',
            'generic_version_of_french' => '',
            'blue_box_french' => '',
            'alternative_dins_non_prescribed_french' => '',
            'strength_french' => '',
            'form_french' => '',
            'pin_slf' => '',
            'pin_clic' => '',
            'gx_available_on_the_market' => '',
            'notes_on_rg_select' => '',
            'vaccines_used_to_protect_against' => '',
            'vaccines_used_to_protect_against_french' => '',
            'rationale_code' => '',
            'rationale' => '',
            'rationale_french' => '',
            'quantity_limits_days' => '',
            'used_for_code' => '',
            'specialty_drug' => '',
            'patient_support_program' => '',
            'special_distribution_program' => '',
        ];
    }
}
