<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WorkflowNodesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        \DB::table('workflow_nodes')->delete();

        \DB::table('workflow_nodes')->insert([
            0 => [
                'id' => 1,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 20,
                'label' => 'New',
                'type' => 'EditableNodeInput',
            ],
            1 => [
                'id' => 2,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 80,
                'label' => 'Contact Customer',
                'type' => 'EditableNodeDefault',
            ],
            2 => [
                'id' => 3,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 140,
                'label' => 'Select A car',
                'type' => 'EditableNodeDefault',
            ],
            3 => [
                'id' => 4,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 240,
                'label' => 'Quote',
                'type' => 'EditableNodeDefault',
            ],
            4 => [
                'id' => 5,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 190,
                'label' => 'Test Drive',
                'type' => 'EditableNodeDefault',
            ],
            5 => [
                'id' => 6,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 310,
                'label' => 'Sell',
                'type' => 'EditableNodeDefault',
            ],
            6 => [
                'id' => 7,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 370,
                'label' => 'Finalize Paper Work',
                'type' => 'EditableNodeDefault',
            ],
            7 => [
                'id' => 8,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 150,
                'position_y' => 420,
                'label' => 'Deliver Car',
                'type' => 'EditableNodeOutput',
            ],
            8 => [
                'id' => 9,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 400,
                'position_y' => 210,
                'label' => 'Re-negotiate Price',
                'type' => 'EditableNodeDefault',
            ],
            9 => [
                'id' => 10,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 390,
                'position_y' => 140,
                'label' => 'Choose Another Car',
                'type' => 'EditableNodeDefault',
            ],
            10 => [
                'id' => 11,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => -130,
                'position_y' => 210,
                'label' => 'Cancelled',
                'type' => 'EditableNodeOutput',
            ],
            11 => [
                'id' => 12,
                'created_at' => '2022-10-11 03:29:23',
                'updated_at' => '2022-10-11 03:29:23',
                'workflow_id' => 1,
                'position_x' => 390,
                'position_y' => 380,
                'label' => 'Cancel After Sale',
                'type' => 'EditableNodeOutput',
            ],
            12 => [
                'id' => 13,
                'created_at' => '2022-12-11 23:44:50',
                'updated_at' => '2022-12-11 23:44:50',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 80,
                'label' => 'New',
                'type' => 'EditableNodeInput',
            ],
            13 => [
                'id' => 14,
                'created_at' => '2022-12-11 23:44:50',
                'updated_at' => '2022-12-11 23:44:50',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 140,
                'label' => 'Acknowledged',
                'type' => 'EditableNodeDefault',
            ],
            14 => [
                'id' => 15,
                'created_at' => '2022-12-11 23:44:50',
                'updated_at' => '2022-12-11 23:44:50',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 200,
                'label' => 'In Progress',
                'type' => 'EditableNodeDefault',
            ],
            15 => [
                'id' => 16,
                'created_at' => '2022-12-11 23:44:50',
                'updated_at' => '2022-12-11 23:44:50',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 260,
                'label' => 'Quoted',
                'type' => 'EditableNodeDefault',
            ],
            16 => [
                'id' => 19,
                'created_at' => '2023-01-29 23:21:55',
                'updated_at' => '2023-01-29 23:21:55',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 380,
                'label' => 'Completed',
                'type' => 'EditableNodeOutput',
            ],
            17 => [
                'id' => 21,
                'created_at' => '2023-01-29 23:23:55',
                'updated_at' => '2023-01-29 23:23:55',
                'workflow_id' => 2,
                'position_x' => 80,
                'position_y' => 380,
                'label' => 'Cancel After Sale',
                'type' => 'EditableNodeOutput',
            ],
            18 => [
                'id' => 17,
                'created_at' => '2022-12-11 23:44:50',
                'updated_at' => '2023-01-29 23:23:55',
                'workflow_id' => 2,
                'position_x' => 290,
                'position_y' => 320,
                'label' => 'Sale Approved',
                'type' => 'EditableNodeDefault',
            ],
            19 => [
                'id' => 20,
                'created_at' => '2023-01-29 23:23:55',
                'updated_at' => '2023-01-29 23:35:42',
                'workflow_id' => 2,
                'position_x' => 80,
                'position_y' => 320,
                'label' => 'Cancel before Sale',
                'type' => 'EditableNodeOutput',
            ],
            20 => [
                'id' => 22,
                'created_at' => '2023-01-30 00:00:16',
                'updated_at' => '2023-01-30 00:00:16',
                'workflow_id' => 2,
                'position_x' => 80,
                'position_y' => 260,
                'label' => 'Cancelled',
                'type' => 'EditableNodeOutput',
            ],
        ]);
    }
}
