export const Styles = {
    root: 'flex flex-col w-full min-h-screen flex p-4',
    form: 'w-full lg:w-4/12 px-6 shadow-lg rounded-lg bg-gray-300 flex flex-col py-10 items-center',
    fields: 'mb-3 w-full p-1',
    switch_field: 'mb-3 p-1',
    loading: 'flex items-center justify-center h-80',
    loadingIcon: 'animate-spin 5-x text-indigo-200',
    row: 'flex flex-col md:flex-row mb-2',
    column: 'flex-1 m-2',
    link: 'text-sm font-medium text-purple-600 dark:text-purple-400 hover:underline',
    spacer: 'mb-6',
    h1: 'mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300',
    h2: 'mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300',
    h3: 'mb-4 text-md font-semibold text-gray-600 dark:text-gray-300',
};
